import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'The Scholar',
      'get_started': 'Get Started',
      'sign_in': 'Sign in to existing account',
      'onboarding_title': 'Elite Education for the Modern Era',
      'onboarding_subtitle': 'Access lectures and materials anytime, anywhere.',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email Address',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don’t have an account?',
      'already_have_account': 'Already have an account?',
      'welcome_back': 'Welcome back,',
      'welcome_student': 'Welcome back,\nJulian!',
      'welcome_professor': 'Welcome back,\nProfessor!',
      'featured_lectures': 'Featured Lectures',
      'categories': 'Explore Categories',
      'recent_lectures': 'Recent Lectures',
      'search_hint': 'Search for courses, tutors, or topics...',
      'view_all': 'View All',
      'my_lectures': 'My Lectures',
      'new_questions': 'New Questions',
      'overview': 'Overview',
      'total_students': 'TOTAL STUDENTS',
      'active_lectures': 'ACTIVE LECTURES',
      'new_lecture': 'New Lecture',
      'student_dashboard': 'Student',
      'instructor_dashboard': 'Instructor',
      'lectures': 'Lectures',
      'chat': 'AI Chat',
      'profile': 'Profile',
      'account_settings': 'Account Settings',
      'language': 'Language',
      'appearance': 'Appearance',
      'notifications': 'Notifications',
      'security_legal': 'Security & Legal',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'materials': 'Materials',
      'chat_welcome': "I've summarized the lecture for you. Would you like me to explain any section in more detail?",
      'key_insight': 'Key Insight',
      'up_next': 'UP NEXT IN THIS SERIES',
      'you': 'You',
      'ai_assistant': 'AI Assistant',
      'course_materials': 'Course Materials',
      'messages': 'Messages',
      'academic_luminary': 'Academic Luminary',
      'chat_with_doctor': 'Chat with Doctor',
      'core_curriculum': 'CORE CURRICULUM',
      'lead_instructor': 'Lead Instructor',
      'lectures_tab': 'Lectures',
      'materials_tab': 'Materials (PDFs)',
      'ai_tutor_tab': 'AI Tutor',
      'curriculum_progress': 'Curriculum Progress',
      'subject_materials': 'Subject Materials',
      'ai_tutor_title': 'AI Study Tutor',
      'subject_performance': 'Subject Performance',
      'syllabus_completed': 'syllabus completed',
      'quick_action': 'QUICK ACTION',
      'lectures_remaining': 'lectures remaining for today.',
      'intelligence': 'INTELLIGENCE',
      'ai_summary': 'AI Summary',
      'my_grades': 'My Grades',
      'uni_news': 'Uni News',
      'todays_schedule': "Today's Schedule",
      'full_calendar': 'Full Calendar',
      'pinned_subjects': 'Pinned Subjects',
      'search_messages': 'Search messages...',
      'all_filter': 'All',
      'professors_filter': 'Professors',
      'groups_filter': 'Groups',
      'students_filter': 'Students',
      'live_session': 'LIVE SESSION',
      'ai_summary_available': 'AI SUMMARY AVAILABLE',
      'stay_connected': 'Stay Connected &\nCollaborative',
      'search_subjects': 'Search for subjects...',
      'semester': 'Semester',
      'skip': 'Skip',
      'next': 'Next',
      'ai_unified': 'AI-UNIFIED',
      'university_id_label': 'UNIVERSITY ID',
      'university_id_hint': 'e.g. 2024-8890',
      'password_label': 'PASSWORD',
      'access_restricted_info': 'Access is restricted to authorized university personnel and students.\n',
      'system_status_label': 'System Status: ',
      'operational': 'Operational',
      'ai_verification_active': 'AI VERIFICATION ACTIVE',
      'scholaris_prime': 'SCHOLARIS PRIME ECOSYSTEM',
      'onboarding_1_title': 'The Digital Campus at Your Fingertips',
      'onboarding_1_description': 'Access all your university resources, lectures, and sections in one integrated platform.',
      'onboarding_2_title': 'Smarter Studying with AI',
      'onboarding_2_description': 'Get instant summaries of your PDFs and answers to your subject-specific questions from our specialized AI tutor.',
      'onboarding_3_title': 'Stay Connected &\nCollaborative',
      'onboarding_3_description': 'Join live lectures, chat directly with your doctors and TAs, and stay updated with notifications.',
      'ai_tutor_active': 'AI TUTOR ACTIVE',
      'instant_summary': 'INSTANT SUMMARY',
      'chat_sample_question': 'Does the exam cover the second module as well?',
      'chat_sample_answer': 'Yes, all modules included.',
      'continue_watching': 'Continue Watching',
      'unanswered_questions': 'Unanswered Questions',
      'all_subjects': 'All Subjects',
      'explore_curriculum': 'Explore your academic curriculum',
      'start_learning': 'START LEARNING',
      'syllabus': 'Syllabus',
      'assignments': 'Assignments',
      'type_your_message': 'Type your message...',
      'online': 'Online',
      'ai_assistant_welcome': 'How can I assist your studies today?',
      'direct_conversations': 'Direct Conversations',
      'search_messages_hint': 'Search group or students...',
    },
    'ar': {
      'app_title': 'المثقف',
      'get_started': 'ابدأ الآن',
      'sign_in': 'تسجيل الدخول لحساب موجود',
      'onboarding_title': 'تعليم نخبوي للعصر الحديث',
      'onboarding_subtitle': 'الوصول إلى المحاضرات والمواد في أي وقت ومن أي مكان.',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'لديك حساب بالفعل؟',
      'welcome_back': 'أهلاً بك مرة أخرى',
      'welcome_student': 'مرحباً بعودتك،\nجوليان!',
      'welcome_professor': 'مرحباً بعودتك،\nيا بروفيسور!',
      'featured_lectures': 'المحاضرات المميزة',
      'categories': 'استكشاف الأقسام',
      'recent_lectures': 'المحاضرات الأخيرة',
      'search_hint': 'ابحث عن الدورات، المدرسين، أو المواضيع...',
      'view_all': 'عرض الكل',
      'my_lectures': 'محاضراتي',
      'new_questions': 'أسئلة جديدة',
      'overview': 'نظرة عامة',
      'total_students': 'إجمالي الطلاب',
      'active_lectures': 'المحاضرات النشطة',
      'new_lecture': 'محاضرة جديدة',
      'student_dashboard': 'طالب',
      'instructor_dashboard': 'مدرس',
      'lectures': 'المحاضرات',
      'chat': 'الدردشة الذكية',
      'profile': 'الملف الشخصي',
      'account_settings': 'إعدادات الحساب',
      'language': 'اللغة',
      'appearance': 'المظهر',
      'notifications': 'التنبيهات',
      'security_legal': 'الأمن والقانون',
      'logout': 'تسجيل الخروج',
      'edit_profile': 'تعديل الملف الشخصي',
      'materials': 'المواد',
      'chat_welcome': 'لقد قمت بتلخيص المحاضرة لك. هل تود أن أشرح أي جزء بمزيد من التفصيل؟',
      'key_insight': 'فكرة جوهرية',
      'up_next': 'التالي في هذه السلسلة',
      'you': 'أنت',
      'ai_assistant': 'المساعد الذكي',
      'course_materials': 'مواد المادة',
      'messages': 'الرسائل',
      'academic_luminary': 'الأكاديمية المضيئة',
      'chat_with_doctor': 'تحدث مع الدكتور',
      'core_curriculum': 'المنهج الأساسي',
      'lead_instructor': 'المحاضر الرئيسي',
      'lectures_tab': 'المحاضرات',
      'materials_tab': 'المواد (PDF)',
      'ai_tutor_tab': 'المساعد الذكي',
      'curriculum_progress': 'تقدم المنهج',
      'subject_materials': 'مواد المادة',
      'ai_tutor_title': 'مساعد الدراسة الذكي',
      'subject_performance': 'أداء المادة',
      'syllabus_completed': 'من المنهج اكتمل',
      'quick_action': 'إجراء سريع',
      'lectures_remaining': 'محاضرات متبقية لليوم.',
      'intelligence': 'ذكاء',
      'ai_summary': 'ملخص ذكي',
      'my_grades': 'درجاتي',
      'uni_news': 'أخبار الجامعة',
      'todays_schedule': 'جدول اليوم',
      'full_calendar': 'التقويم الكامل',
      'pinned_subjects': 'المواد المثبتة',
      'search_messages': 'ابحث عن الرسائل...',
      'all_filter': 'الكل',
      'professors_filter': 'الدكاترة',
      'groups_filter': 'المجموعات',
      'students_filter': 'الطلاب',
      'live_session': 'جلسة مباشرة',
      'ai_summary_available': 'ملخص الذكاء الاصطناعي متاح',
      'stay_connected': 'ابقَ على اتصال\nوتعاون',
      'search_subjects': 'ابحث عن المواد...',
      'semester': 'الفصل الدراسي',
      'skip': 'تخطي',
      'next': 'التالي',
      'ai_unified': 'ذكاء موحد',
      'university_id_label': 'رقم الجامعة',
      'university_id_hint': 'مثال: 2024-8890',
      'password_label': 'كلمة المرور',
      'access_restricted_info': 'يقتصر الدخول على منسوبي وطلاب الجامعة المصرح لهم.\n',
      'system_status_label': 'حالة النظام: ',
      'operational': 'يعمل',
      'ai_verification_active': 'التحقق بالذكاء الاصطناعي مفعل',
      'scholaris_prime': 'نظام سكولاريس برايم المتكامل',
      'onboarding_1_title': 'الحرم الجامعي الرقمي في متناول يدك',
      'onboarding_1_description': 'الوصول إلى جميع موارد الجامعة والمحاضرات والأقسام في منصة واحدة متكاملة.',
      'onboarding_2_title': 'دراسة أذكى مع الذكاء الاصطناعي',
      'onboarding_2_description': 'احصل على ملخصات فورية لملفات الـ PDF وإجابات لأسئلتك الخاصة بالمواد من مساعدنا الذكي المتخصص.',
      'onboarding_3_title': 'ابقَ على اتصال وتعاون',
      'onboarding_3_description': 'انضم إلى المحاضرات المباشرة، وتحدث مباشرة مع الدكاترة والمعيدين، وابقَ على اطلاع دائم بالتنبيهات.',
      'ai_tutor_active': 'المساعد الذكي نشط',
      'instant_summary': 'ملخص فوري',
      'chat_sample_question': 'هل يغطي الامتحان الوحدة الثانية أيضاً؟',
      'chat_sample_answer': 'نعم، جميع الوحدات مشمولة.',
      'continue_watching': 'متابعة المشاهدة',
      'unanswered_questions': 'أسئلة لم يتم الرد عليها',
      'all_subjects': 'جميع المواد',
      'explore_curriculum': 'استكشف منهجك الدراسي الأكاديمي',
      'start_learning': 'ابدأ التعلم',
      'syllabus': 'المنهج',
      'assignments': 'التكليفات',
      'type_your_message': 'اكتب رسالتك...',
      'online': 'متصل',
      'ai_assistant_welcome': 'كيف يمكنني مساعدتك في دراستك اليوم؟',
      'direct_conversations': 'الرسائل المباشرة',
      'search_messages_hint': 'البحث عن مجموعات أو طلاب...',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
